### ISSUE TITLE
 Cannot read property 'ignore' of undefined

### ISSUE THREAD

**Issue by lpmorin** [boardroom-project/boardroom-contracts#2]
When running `npm test`

Here is the output I get

On mac os x 10.10.5

```
Testing...
/Users/lpmorin/Programming/boardroom-contracts/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileS

TypeError: Cannot read property 'ignore' of undefined
    at Workspace.getIgnoreGlobs (/Users/lpmorin/Programming/boardroom-contracts/node_modules/dapple/lib/workspace.js:267:56)
    at getSourcePatterns (/Users/lpmorin/Programming/boardroom-contracts/node_modules/dapple/lib/streams/package_stream.js:31:32)
    at DestroyableTransform._flush (/Users/lpmorin/Programming/boardroom-contracts/node_modules/dapple/lib/streams/package_stream.js:47:20)
    at DestroyableTransform.<anonymous> (/Users/lpmorin/Programming/boardroom-contracts/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/Users/lpmorin/Programming/boardroom-contracts/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/Users/lpmorin/Programming/boardroom-contracts/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
    at endWritable (/Users/lpmorin/Programming/boardroom-contracts/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)
```

**Comment by SilentCicero** [comment]
@lpmorin this is a problem with dapple @nmushegian may have insight ^^

**Comment by nmushegian** [comment]
Maybe there is no dappfile or you have an old dapple version?

`Cannot read property "ignore" of undefined`  it's trying to read something off of a dappfile object somewhere

**Comment by ShrutiAppiah** [comment]
I have a dappfile, and v0.7.2 and I get the same error

**Comment by SilentCicero** [comment]
It's because the dappfile is in the same dir as the node_modules :*( @nmushegian ... I'm running dapple locally now. This should be fixed.
